apiVersion: v1.2
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  namespace: kubeflow
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

